spring:
  profiles:
    default: local

  # \uB514\uD3F4\uD2B8\uB294 local\uC774\uACE0 \uD14C\uC2A4\uD2B8\uB294 \uC544\uB798 test\uD504\uB85C\uD30C\uC77C\uB85C \uB3CC\uB9AC\uB3C4\uB85D \uD558\uACE0 \uC704\uB294 \uACF5\uC6A9\uC774\uB2E4.
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: none
  # ddl-auto: \uAE30\uC874 \uD14C\uC774\uBE14 \uC0AD\uC81C\uD6C4 \uB2E4\uC2DC \uC0DD\uC131 (Drop + create)
server:
  port: 8081
---
spring:
  config:
    activate:
      on-profile: local
  sql:
    init:
      encoding: utf-8

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true # (2.5) Hibernate \uCD08\uAE30\uD654 \uC774\uD6C4 data.sql \uC2E4\uD589
    # \uC11C\uBC84 \uC2E4\uD589\uD558\uBA74 \uBA87\uAC1C\uC529 \uC0DD\uC131\uD558\uAE30 \uC5B4\uB824\uC6B0\uB2C8\uAE4C data.sql\uC744 \uC2E4\uD589\uC2DC\uCF1C\uC90C
    # \uC124\uC815\uC774 false \uC774\uBA74 \uD558\uC774\uBC84\uB124\uC774\uD2B8 \uCD08\uAE30\uD654 \uC774\uC804 data.sql\uC774 \uC2E4\uD589\uC774 \uB418\uB294\uB370
    # \uADF8\uB7EC\uBA74 \uC5D0\uB7EC\uAC00 \uBC1C\uC0DD\uD55C\uB2E4. jpa\uB97C \uC0AC\uC6A9\uD558\uACE0 \uC788\uC5B4\uC11C \uD558\uC774\uBC84\uB124\uC774\uD2B8\uAC00 \uCD08\uAE30\uD654 \uB418\uBA74\uC11C ddl sql \uC815\uBCF4\uAC00 \uC788\uC5B4\uC11C
    # \uCFFC\uB9AC\uB97C \uB0A0\uB9B4\uC218 \uC788\uB294\uB370 \uCD08\uAE30\uD654 \uB41C \uB2E4\uC74C\uC5D0 sql\uC744 \uC2E4\uD589\uC2DC\uCF1C\uB2EC\uB77C\uB294 \uAC83.
    # \uD14C\uC2A4\uD2B8\uB54C\uB294 \uC0AC\uC6A9\uD558\uC9C0\uC54A\uB294\uB2E4, \uCD08\uAE30 \uAC1C\uBC1C\uB54C \uD654\uBA74\uC744 \uBE68\uB9AC\uBE68\uB9AC \uBCFC\uB54C \uC0AC\uC6A9\uD55C\uB2E4.
  h2:
    console:
      enabled: true
      path: /h2-console
    # \uC11C\uBC84\uB97C \uB4E4\uC5B4\uAC00\uC11C h2\uB97C \uCF58\uC194\uB85C \uC811\uADFC\uD560\uAC83\uC778\uC9C0 true

---

spring:
  config:
    activate:
      on-profile: test

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: never
      encoding: utf-8

      # \uD14C\uC2A4\uD2B8\uB294 \uC9C1\uC811 \uD14C\uC774\uD130\uB97C \uB123\uACE0 \uD14C\uC2A4\uD2B8\uB97C \uD558\uAE30\uB54C\uBB38\uC5D0 sql\uC744 \uC544\uC608 \uC2E4\uD589\uD558\uC9C0 \uC54A\uB294\uB2E4.
logging:
  level:
    org:
      springframework:
        jdbc:
          support:
            JdbcTransactionManager: TRACE